In [18]:
import tensorflow as tf

x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],
         [1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

X = tf.placeholder("float",[None,4])
Y = tf.placeholder("float",[None,3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4,nb_classes]),name = "weight")
b = tf.Variable(tf.random_normal([nb_classes]),name = "bias")

#tf.nn.softmax computes softmax activations
#softmax = exp(logits) / reduce_sum(exp(logits),dim)
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

#Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

#launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) ##글로벌 함수 초기화
    
    for step in range(2001):
        sess.run(optimizer,feed_dict = {X:x_data, Y:y_data})
        if step%200 == 0:
            print(step,sess.run(cost,feed_dict = {X:x_data, Y:y_data}))
    a = sess.run(hypothesis, feed_dict = {X:x_data})
    print(sess.run(tf.arg_max(a,1))) ##max argument 찾기 (axis 1 에서)
    b = sess.run(hypothesis, feed_dict = {X:[[1,11,7,9]]}) 
    print(b,sess.run(tf.arg_max(b,1)))
    al =  sess.run(hypothesis, feed_dict = {X:[[1,11,7,9],[1,3,4,3],[1,1,0,1]]})
    print(al,sess.run(tf.arg_max(al,1)))


0 4.1160064
200 0.53875387
400 0.4472188
600 0.3727746
800 0.30113554
1000 0.23790647
1200 0.21491407
1400 0.19610278
1600 0.18021077
1800 0.16661672
2000 0.15486494
[2 2 2 1 1 1 0 0]
[[2.0937028e-03 9.9789822e-01 8.1202652e-06]] [1]
[[2.0937028e-03 9.9789822e-01 8.1202652e-06]
 [9.1657829e-01 7.6912120e-02 6.5095373e-03]
 [1.4539349e-08 3.1984726e-04 9.9968016e-01]] [1 0 2]
