In [25]:
import numpy as np

xy = np.loadtxt('sample_test_score01.csv', delimiter =',', dtype = np.float32)
x_data = xy[:, 0:-1] #처음 슬라이스는 행 다음슬라이스는 열을 의미하는듯 (모든 행을 가져온 것.)
y_data = xy[:, -1:]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(5, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 5
(5, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [27]:
import tensorflow as tf

X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])
W = tf.Variable(tf.random_normal(shape = [3,1]), name = "weight")
b = tf.Variable(tf.random_normal(shape = [1]), name = "bias")

hy = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hy - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hy, train], feed_dict = {X : x_data, Y: y_data})
    if step %100 == 0:
        print(step, cost_val, hy_val)

0 139901.52 [[-182.5053 ]
 [-213.00417]
 [-213.45822]
 [-230.39027]
 [-162.28348]]
100 2.051722 [[149.40843]
 [185.86525]
 [179.58948]
 [197.61931]
 [141.94487]]
200 2.009124 [[149.44287]
 [185.84218]
 [179.60071]
 [197.62218]
 [141.91904]]
300 1.9684842 [[149.47644]
 [185.81969]
 [179.61166]
 [197.62485]
 [141.89395]]
400 1.9297216 [[149.50916]
 [185.79776]
 [179.62236]
 [197.62735]
 [141.86961]]
500 1.8926966 [[149.54108]
 [185.77641]
 [179.63281]
 [197.62967]
 [141.84601]]
600 1.8573548 [[149.57222]
 [185.75562]
 [179.64304]
 [197.63187]
 [141.8231 ]]
700 1.8235925 [[149.60257]
 [185.73534]
 [179.653  ]
 [197.63387]
 [141.80089]]
800 1.7913401 [[149.63216]
 [185.71556]
 [179.66273]
 [197.63571]
 [141.77934]]
900 1.7605283 [[149.66101]
 [185.6963 ]
 [179.67224]
 [197.63742]
 [141.75842]]
1000 1.731065 [[149.68915]
 [185.67752]
 [179.68152]
 [197.63898]
 [141.73813]]
1100 1.7028654 [[149.71661]
 [185.65924]
 [179.69061]
 [197.6404 ]
 [141.71848]]
1200 1.6758906 [[149.74338]
 [185.6413

In [ ]:
#EXAM1, EXAM2, EXAM3, FINAL
73,80,75,152
93,88,93,185
89,91,90,180
96,98,100,196
73,66,70,142


0 cost: 65243.7265625 
 hypothesis: [[ -87.00422 ]
 [-113.203804]
 [-106.759384]
 [-120.13349 ]
 [ -69.953804]] 
200 cost: 421.4227600097656 
 hypothesis: [[145.53004]
 [167.30315]
 [169.10205]
 [180.29034]
 [ 88.071  ]] 
400 cost: 415.9595642089844 
 hypothesis: [[145.04918 ]
 [167.68402 ]
 [168.98294 ]
 [180.15506 ]
 [ 88.571945]] 
600 cost: 410.990966796875 
 hypothesis: [[144.599   ]
 [168.0447  ]
 [168.87396 ]
 [180.02391 ]
 [ 89.037926]] 
800 cost: 406.4566955566406 
 hypothesis: [[144.17757]
 [168.38644]
 [168.77438]
 [179.89664]
 [ 89.47121]] 
1000 cost: 402.30450439453125 
 hypothesis: [[143.78296]
 [168.71042]
 [168.68356]
 [179.77301]
 [ 89.87389]] 
1200 cost: 398.48687744140625 
 hypothesis: [[143.41351]
 [169.01782]
 [168.60098]
 [179.6528 ]
 [ 90.24799]] 
1400 cost: 394.96368408203125 
 hypothesis: [[143.06757 ]
 [169.30968 ]
 [168.52611 ]
 [179.53581 ]
 [ 90.595375]] 
1600 cost: 391.6995849609375 
 hypothesis: [[142.7436  ]
 [169.58696 ]
 [168.45842 ]
 [179.42186 ]
 [ 90