In [1]:
import tensorflow as tf
import numpy as np

In [45]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

#Evaluation our model using test dataset
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

X = tf.placeholder("float",[None,3])
Y = tf.placeholder("float",[None,3])
W = tf.Variable(tf.random_normal([3,3]),dtype = tf.float32)
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.05).minimize(cost)

#Corrent prediction Test model
prediction = tf.argmax(hypothesis,1)
is_correct = tf.equal(prediction,tf.argmax(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))

#launch graph
with tf.Session() as sess:
    #Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, W_val, _, hy_val = sess.run([cost,W,optimizer,hypothesis],feed_dict = {X:x_data, Y:y_data})
        if step%400==0:
            print(step,cost_val,W_val)
    print(hy_val)
    #prediction
    print("Prediction: ",sess.run(prediction,feed_dict = {X:x_test}))
    #Calculate the accuracy
    print("Accuracy: {:.2%}".format(sess.run(accuracy,feed_dict = {X:x_test, Y:y_test})))
##계속 accuracy가 너무 낮게 나왔던 이유: for문안의 training을 if문 안에 넣어버려서 학습이 몇번 이뤄지지 않게 되어버림      
#밖에 놓아서 반복이 가능하게하니 acc 100%

0 2.4362109 [[ 0.06107718 -0.15862946 -1.6793253 ]
 [-0.84010285 -1.6594412  -0.5215618 ]
 [-0.73910797  0.6800976  -0.2817133 ]]
400 0.6430323 [[-1.7704797  -0.18925242  0.18285593]
 [-0.874585   -1.0735958  -1.0729239 ]
 [ 0.17046432  0.17710106 -0.6882891 ]]
800 0.5211192 [[-2.5682573  -0.08277263  0.8741509 ]
 [-0.8492161  -1.0253568  -1.1465331 ]
 [ 0.45433146  0.11969226 -0.9147473 ]]
1200 0.45508632 [[-3.170425    0.03390167  1.3596404 ]
 [-0.8513607  -1.0035015  -1.1662431 ]
 [ 0.68508846  0.07407075 -1.0998832 ]]
1600 0.40943423 [[-3.673743    0.13806997  1.7587898 ]
 [-0.8551784  -0.99023676 -1.1756897 ]
 [ 0.8786749   0.03702214 -1.2564195 ]]
2000 0.3750204 [[-4.1104517   0.22703263  2.1065323 ]
 [-0.8581047  -0.981239   -1.1817595 ]
 [ 1.0459824   0.00720357 -1.3939106 ]]
[[4.71771928e-05 1.05870888e-02 9.89365697e-01]
 [7.16943468e-04 5.03622070e-02 9.48920786e-01]
 [5.03092483e-02 4.42990184e-01 5.06700635e-01]
 [2.56621778e-01 6.25357330e-01 1.18020914e-01]
 [3.17905635e

In [50]:
#learning rate 크게해본 버전
# Lab 7 Learning rate and Evaluation
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=2.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        if step%40 == 0:
            #cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
            print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: {:.2%}".format(sess.run(accuracy, feed_dict={X: x_test,Y:y_test})))


0 3.388558 [[-3.2859426   1.0989507  -0.22410768]
 [-3.8908763   2.9255838   1.6960953 ]
 [-5.199213    2.853474    1.3409916 ]]
40 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
80 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
120 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
160 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
200 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
Prediction: [0 0 0]
Accuracy: 0.00%
