In [13]:
import tensorflow as tf
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

X = tf.placeholder(tf.float32, shape = [None, 2])
Y = tf.placeholder(tf.float32, shape = [None, 1])
W = tf.Variable(tf.random_normal([2,1]), name = "weight")
b = tf.Variable(tf.random_normal([1], name = "bias"))  ## dot(X,W) + b 식에서 형태 유추

# Hy using sigmoid: tf.div(1., 1+tf.exp(tf.matmul(X, W) + b)) 과 동일
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

#cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * \
                      tf.log(1 - hypothesis))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = optimizer.minimize(cost)

#Accuacy computation
#True if hy > 0.5 else False ## hy값이 0.5보다 크면 1로 추정, 나머지 0
predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32) #True -> 1, False -> 0

# equal이면 1반환 (1이면 100%) 
## tf.cast(조건,dtype = tf.float32) : 조건이 참이면 1, 거짓이면 0 반환.
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float32))

with tf.Session() as sess:
    #initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict = {X : x_data, Y : y_data})
        #if step%200 == 0:
        #    print(step,"cost : ", cost_val)
    #Accuract report
    h, c, a = sess.run([hypothesis, predicted, accuracy],feed_dict = {X : x_data, Y : y_data})
    print("Hypothesis : {}\npredicted : {}, \naccuracy : {}".format(h,c,a))

Hypothesis : [[0.03134207]
 [0.15965272]
 [0.3077384 ]
 [0.7800745 ]
 [0.9387484 ]
 [0.9798923 ]]
predicted : [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]], 
accuracy : 1.0


In [7]:
#Logistic Regression 혼자 짜보기! 도전
import tensorflow as tf
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

X = tf.placeholder(shape = [None, 2], dtype = tf.float32)
Y = tf.placeholder(tf.float32, shape = [None, 1])
W = tf.Variable(tf.random_normal([2,1]), name = "weight")
b = tf.Variable(tf.random_normal([1]), name = "bias")

hy = tf.sigmoid(tf.matmul(X,W) + b)
# hy = div(1., 1 + tf.exp(tf.matmul(X,W) + b))
cost = -tf.reduce_mean(Y*tf.log(hy) + (1-Y)*tf.log(1 - hy))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

predicted = tf.cast(hy > 0.5, dtype =tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float32))
for step in range(10001):
    cost_val, hy_val, _ = sess.run([cost, hy, train], feed_dict = {X : x_data, Y : y_data})
    if step %2000 == 0:
        print(step,cost_val,hy_val)
        
h, p, a = sess.run([hy, predicted, accuracy], feed_dict = {X:x_data, Y: y_data})
print(h,"\n",p,"\n",a)


0 1.184308 [[0.9005957 ]
 [0.88598275]
 [0.76462376]
 [0.77975327]
 [0.704989  ]
 [0.55936027]]
2000 0.47567427 [[0.22541395]
 [0.22051309]
 [0.7807557 ]
 [0.5958266 ]
 [0.7709173 ]
 [0.947478  ]]
4000 0.340547 [[0.13417056]
 [0.2078368 ]
 [0.63562053]
 [0.6518123 ]
 [0.83334607]
 [0.954696  ]]
6000 0.25806466 [[0.08599309]
 [0.19802175]
 [0.5080809 ]
 [0.6988452 ]
 [0.87675565]
 [0.9622287 ]]
8000 0.20576341 [[0.05744449]
 [0.18417978]
 [0.4144704 ]
 [0.7348859 ]
 [0.9066561 ]
 [0.9698751 ]]
10000 0.17059195 [[0.04009284]
 [0.16986217]
 [0.34689036]
 [0.7627869 ]
 [0.9272593 ]
 [0.9761288 ]]
[[0.04008605]
 [0.16985515]
 [0.3468615 ]
 [0.7627992 ]
 [0.9272678 ]
 [0.97613156]] 
 [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
 1.0


In [18]:
##logistic 복습.
import tensorflow as tf
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

X = tf.placeholder(tf.float32,shape = [None,2])
Y = tf.placeholder(tf.float32,shape = [None,1])
W = tf.Variable(tf.random_normal([2,1]),name = "Weight")
b = tf.Variable(tf.random_normal([1]),name = "bias")

Hypothesis = tf.sigmoid(tf.matmul(X,W)+b)

cost = -tf.reduce_mean(Y*tf.log(Hypothesis)+(1-Y)*tf.log(1-Hypothesis))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

Predicted = tf.cast(Hypothesis > 0.5,dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(Predicted,Y),dtype = tf.float32))

for step in range(10000):
    #sess.run(train)
    cost_val, hy_val, _ = sess.run([cost,Hypothesis,train], feed_dict = {X:x_data, Y:y_data})
    if step%2000 == 0:
        print(step)
        print(cost_val,"\n", hy_val)
        
hy,p,a = sess.run([Hypothesis,Predicted,accuracy], feed_dict = {X:x_data,Y:y_data})
print(h,p,a)

0
1.8117026 
 [[0.05387346]
 [0.0104174 ]
 [0.34227598]
 [0.01471395]
 [0.01747591]
 [0.12009133]]
2000
0.42285427 
 [[0.17827429]
 [0.20297383]
 [0.7411388 ]
 [0.6127827 ]
 [0.7977744 ]
 [0.9543054 ]]
4000
0.30839357 
 [[0.1147302 ]
 [0.20452864]
 [0.58968   ]
 [0.66873366]
 [0.84977126]
 [0.95723844]]
6000
0.23800325 
 [[0.07473538]
 [0.19355284]
 [0.47329634]
 [0.71199185]
 [0.8880684 ]
 [0.96491575]]
8000
0.19251136 
 [[0.05068156]
 [0.17931949]
 [0.38940808]
 [0.74499625]
 [0.91440403]
 [0.9721448 ]]
[[0.03134207]
 [0.15965272]
 [0.3077384 ]
 [0.7800745 ]
 [0.9387484 ]
 [0.9798923 ]] [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 1.0
