In [1]:
import numpy as np
import tensorflow as tf


C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [9]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
import pprint as pp
pp.pprint(t)
print("rank: ",t.ndim)
print("shape: ",t.shape)
print(t[0],t[-1],t[1:5])

array([0., 1., 2., 3., 4., 5., 6.])
rank:  1
shape:  (7,)
0.0 6.0 [1. 2. 3. 4.]


In [12]:
t = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
pp.pprint(t) 

print("rank: ",t.ndim)  #number of dimension?
print("shape: ",t.shape)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
rank:  2
shape:  (4, 3)


In [16]:
sess = tf.Session()

In [17]:
#Shape, Rank, Axis !!!
t = tf.constant([1,2,3,4]) # rank 1 ->shape:(?)
tf.shape(t).eval(session = sess)

array([4])

In [20]:
t = tf.constant([[1,2],[3,4]]) # rank 2 ->shape:(?,?)
tf.shape(t).eval(session = sess)

array([2, 2])

In [21]:
t = tf.constant([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
tf.shape(t).eval(session = sess)

array([2, 3, 4])

In [22]:
#Axis : rank1,2,3,4... 
#axis 0 : 처음 축
#axis 1 : 두번째 축
# ... axis -1 : 가장 안쪽의 축(rank)

In [23]:
#mat1*mat2 의 결과는 행렬의 곱이 아님 (rank를 맞추어주는 broadcasting에 의해서 이상한 결과가 나옴)
#tf.matmul(mat1,mat2)로 해줘야함


In [25]:
#Reduce_mean
tf.reduce_mean([1.,2.],axis=0).eval(session=sess)

1.5

In [34]:
x = [[[1.,2.,3.],
     [4.,5.,6.]]]
print(tf.reduce_mean(x).eval(session=sess)) #flatten
print(tf.reduce_mean(x,axis = 0).eval(session=sess))
print(tf.reduce_mean(x,axis = 1).eval(session=sess))
print(tf.reduce_mean(x,axis = 2).eval(session=sess))
print(tf.reduce_mean(x,axis = -1).eval(session=sess))

3.5
[[1. 2. 3.]
 [4. 5. 6.]]
[[2.5 3.5 4.5]]
[[2. 5.]]
[[2. 5.]]


In [36]:
x = [[[1.,2.,3.],
     [4.,5.,6.]]]
print(tf.reduce_sum(x).eval(session=sess)) #flatten
print(tf.reduce_sum(x,axis = 0).eval(session=sess))
print(tf.reduce_sum(x,axis = 1).eval(session=sess))
print(tf.reduce_sum(x,axis = 2).eval(session=sess))
print(tf.reduce_sum(x,axis = -1).eval(session=sess))

21.0
[[1. 2. 3.]
 [4. 5. 6.]]
[[5. 7. 9.]]
[[ 6. 15.]]
[[ 6. 15.]]


In [37]:
y = [[1.,2.],
    [3.,4.]]
tf.reduce_mean(tf.reduce_sum(y,axis=-1)).eval(session=sess)

5.0

In [42]:
#argmax
x = [[0,1,2],
     [2,3,0]]
tf.argmax(x,axis=0).eval(session=sess)

array([1, 1, 0], dtype=int64)

In [43]:
tf.argmax(x,axis=1).eval(session=sess)

array([2, 1], dtype=int64)

In [47]:
t = np.array([[[0,1,2],
               [3,4,5]],
             [[6,7,8],
              [9,10,11]]])
t.shape

(2, 2, 3)

In [49]:
tf.reshape(t,shape = [-1,3]).eval(session=sess) 
#-1은 자동으로 맟주라는 의미

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
tf.reshape(t, shape = [-1,1,3]).eval(session=sess)
#shape = (?,?,...,*)마지막 숫자인 * 만 안바뀌면 데이터가 손상되지 않음

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [52]:
tf.squeeze([[0],[1],[2]]).eval(session = sess)

array([0, 1, 2])

In [55]:
tf.expand_dims([0,1,2],1).eval(session=sess)

array([[0],
       [1],
       [2]])

In [56]:
tf.one_hot([[0],[1],[2],[0]], depth=3).eval(session=sess)
#rank가 하나 늘어있음

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [58]:
tf.reshape(t,shape=[-1,3]).eval(session=sess)
#reshape으로 랭크를 다시 조정

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
#int32로 바꾸기
print(tf.cast([1.0,2.2,3.3,4.8],tf.int32).eval(session=sess))

#조건을 1,0 으로 바꾸기
print(tf.cast([True,False,1==1,1==0],dtype = tf.float32).eval(session=sess))

[1 2 3 4]
[1. 0. 1. 0.]


In [66]:
#Stack
x=[1,4]
y=[2,5]
z=[3,6]

#Pack along first dimension
tf.stack([x,y,z]).eval(session=sess)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [70]:
print(tf.stack([x,y,z],axis=0).eval(session=sess))
print(tf.stack([x,y,z],axis=1).eval(session=sess))


[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [71]:
x = [[3,6,1],
    [0,5,7]]
tf.ones_like(x).eval(session=sess) #x닯은 1행렬

array([[1, 1, 1],
       [1, 1, 1]])

In [72]:
tf.zeros_like(x).eval(session=sess) #x닮은 0행렬

array([[0, 0, 0],
       [0, 0, 0]])

In [74]:
for x,y in zip([1,2,3],[4,5,6]):
    print(x,y)

for x,y,z in zip([1,2,3],[4,5,6],[7,8,9]):
    print(x,y,z)

1 4
2 5
3 6
1 4 7
2 5 8
3 6 9
