In [1]:
import tensorflow as tf
import numpy as np

In [17]:
tf.set_random_seed(777) # for reproducibility

#Non-normalized inputs
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
#xy = MinMaxScaler(xy)

x_data = xy[:,:-1]
y_data = xy[:,[-1]]

X = tf.placeholder("float",shape = [None,4])
Y = tf.placeholder("float",shape = [None,1])
W = tf.Variable(tf.random_normal([4,1]),dtype = tf.float32,name = "weight")
b = tf.Variable(tf.random_normal([1]),dtype = tf.float32,name="bias")

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(Y-hypothesis))
#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer,feed_dict = {X:x_data,Y:y_data})
        if step%400==0:
            cost_val, hy_val = sess.run([cost,hypothesis],feed_dict = {X:x_data,Y:y_data})
            print(cost_val,hy_val)
#normalize 되어있지않은 큰값의 x input이 들어있어서 이상한 값이 나와버림



7.842295e+26 [[1.9753901e+13]
 [3.9766632e+13]
 [3.1282973e+13]
 [2.1929199e+13]
 [2.5844733e+13]
 [2.6062262e+13]
 [2.3886964e+13]
 [3.0412854e+13]]
nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]


In [24]:
from sklearn.preprocessing import MinMaxScaler #normalize 하기위해 import

tf.set_random_seed(777) # for reproducibility

#Non-normalized inputs(세번째 x data가 자릿수가 너무 다름)
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
xy=MinMaxScaler().fit_transform(xy) ##잘 모르지만 이런식으로 normalize 가능
##xy의 데이터들을 min0,max1사이의 값들로 변환 (x-u)/σ 등의 정규화 같은 변환 -> 적당한 learning rate 존재함
print(xy)
x_data = xy[:,:-1]
y_data = xy[:,[-1]]

X = tf.placeholder("float",shape = [None,4])
Y = tf.placeholder("float",shape = [None,1])
W = tf.Variable(tf.random_normal([4,1]),dtype = tf.float32,name = "weight")
b = tf.Variable(tf.random_normal([1]),dtype = tf.float32,name="bias")

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(Y-hypothesis))
#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.05).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(200001):
        sess.run(optimizer,feed_dict = {X:x_data,Y:y_data})
        if step%40000==0:
            cost_val, hy_val = sess.run([cost,hypothesis],feed_dict = {X:x_data,Y:y_data})
            print(cost_val,hy_val)
#참고로 learning rate를 1e-5로 했을때는 학습이 잘 안되었음. 1e-2정도에서 잘 되는듯.    
    

[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
1.3442793 [[-0.2797042 ]
 [ 0.34282207]
 [-0.3188163 ]
 [-1.0474745 ]
 [-0.65968484]
 [-0.66163254]
 [-1.2952045 ]
 [-1.0000467 ]]
0.0027721613 [[0.98980194]
 [0.82266164]
 [0.6284753 ]
 [0.405787  ]
 [0.55583274]
 [0.46814662]
 [0.14461583]
 [0.02587493]]
0.0027506922 [[0.99017024]
 [0.82360363]
 [0.6300689 ]
 [0.41238433]
 [0.55469203]
 [0.4604162 ]
 [0.14292188]
 [0.02692471]]
0.002749745 [[0.9902461 ]
 [0.82380086]
 [0.6304035 ]
 [0.4137693 ]
 [0.5544532 ]
 [0.4587937 ]
 [0.14256777]
 [0.0271443 ]]
0.0027497034 [[0.9902607 ]
